pipeline {
    agent any

    stages {
        stage('Docker Pull Calculator Image') {
            steps {
                sh '''#!/bin/bash
                    if [ "$(docker images -q gabsss/go-calculator:latest)" == "" ];
                    then docker pull gabsss/go-calculator:latest
                '''
            }
        }

        stage('Docker Run Calculator Image') {
            steps {
                sh '''#!/bin/bash
                     if ["$(docker ps -q -f name=go_calculator)" == ""];
                    then
                        docker rm -f go_calculator
                        docker run --name=go_calculator --network=host -p 8000:8000 gabsss/go-calculator:latest
                 '''
            }
        }
    }
}