pipeline {
    environment { 
        DOCKERHUB_REPOSITORY = credentials('Repository_Name')
    }

    agent any

    stages {
        stage('Docker Pull Calculator Image') {
            steps {
                sh '''#!/bin/bash
                    if [ "$(docker images -q $DOCKERHUB_REPOSITORY:latest)" == "" ];
                    then 
                        docker pull $DOCKERHUB_REPOSITORY:latest
                    fi
                '''
            }
        }

        stage('Docker Run Calculator Image') {
            steps {
                sh '''#!/bin/bash
                     if ["$(docker ps -q -f name=go_calculator)" == ""];
                    then
                        docker rm -f go_calculator
                        docker run --name=go_calculator --network=host -p 8000:8000 $DOCKERHUB_REPOSITORY:latest
                    fi
                 '''
            }
        }
    }
}