pipeline {

    agent any

    stages {

        stage('Packer Build Image') {
            steps {
                sh '/var/jenkins_home/tools/biz.neustar.jenkins.plugins.packer.PackerInstallation/Packer_Go-Calculator_linux_amd64/packer init ./build_calculator.pkr.hcl'
                sh '/var/jenkins_home/tools/biz.neustar.jenkins.plugins.packer.PackerInstallation/Packer_Go-Calculator_linux_amd64/packer validate ./build_calculator.pkr.hcl'
                sh '/var/jenkins_home/tools/biz.neustar.jenkins.plugins.packer.PackerInstallation/Packer_Go-Calculator_linux_amd64/packer build ./build_calculator.pkr.hcl'
            }
        }
    }
}