pipeline {
    environment { 
        REPOSITORY = credentials('Reposiory Name')
        DOCKERHUB_CREDENTIALS = credentials('dockerHUB')
    }

    agent any

    stages {
        stage('Packer Build Image') {
            steps {
                sh '/var/jenkins_home/tools/biz.neustar.jenkins.plugins.packer.PackerInstallation/Packer_Go-Calculator_linux_amd64/packer init ./build_calculator.pkr.hcl'
                sh '/var/jenkins_home/tools/biz.neustar.jenkins.plugins.packer.PackerInstallation/Packer_Go-Calculator_linux_amd64/packer validate ./build_calculator.pkr.hcl'
                sh '/var/jenkins_home/tools/biz.neustar.jenkins.plugins.packer.PackerInstallation/Packer_Go-Calculator_linux_amd64/packer build -var REPOSITORY=$REPOSITORY  -var USERNAME=$DOCKERHUB_CREDENTIALS_USR  -var PASSWORD=$DOCKERHUB_CREDENTIALS_PSW ./build_calculator.pkr.hcl'
            }
        }
    }
}